"""add closest 1000 table

Revision ID: 342c9a594f33
Revises: 6777d9f1937f
Create Date: 2025-06-09 16:36:45.379902

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "342c9a594f33"
down_revision: Union[str, None] = "6777d9f1937f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "closest1000",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("secret_word_id", sa.Integer(), nullable=False),
        sa.Column("out_of_1000", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_word_id"],
            ["secretword.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_closest1000_secret_word_id"),
        "closest1000",
        ["secret_word_id"],
        unique=False,
    )
    op.create_index(op.f("ix_closest1000_word"), "closest1000", ["word"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_closest1000_word"), table_name="closest1000")
    op.drop_index(op.f("ix_closest1000_secret_word_id"), table_name="closest1000")
    op.drop_table("closest1000")
    # ### end Alembic commands ###
