"""fine-tune indexes

Revision ID: 6777d9f1937f
Revises: edef17c40466
Create Date: 2024-03-05 17:11:50.533412

"""

from typing import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6777d9f1937f"
down_revision: Union[str, None] = "edef17c40466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_secretword_game_date", table_name="secretword")
    op.drop_index("ux_user_id__game_date", table_name="userhistory")
    op.drop_index("ix_user_email", table_name="user")
    op.create_index(
        "nci_user_id__game_date",
        "userhistory",
        ["user_id", "game_date"],
        unique=False,
        mssql_include=["distance", "egg", "guess", "similarity", "solver_count"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "nci_user_id__game_date",
        table_name="userhistory",
        mssql_include=["distance", "egg", "guess", "similarity", "solver_count"],
    )
    op.create_index(
        "ux_user_id__game_date", "userhistory", ["user_id", "game_date"], unique=False
    )
    op.create_index("ix_user_email", "user", columns=["email"], unique=True)
    op.create_index(
        "ix_secretword_game_date", "secretword", ["game_date"], unique=False
    )
    # ### end Alembic commands ###
