"""user + user history tables

Revision ID: c4ee2484db71
Revises:
Create Date: 2024-01-09 17:19:56.323607

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4ee2484db71"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(128), nullable=False),
        sa.Column("user_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("picture", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("given_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("family_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_login", sa.DateTime(), nullable=False),
        sa.Column("subscription_expiry", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "userhistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "guess",
            sa.String(
                32,
                # collation="Hebrew_100_CI_AI_SC_UTF8",
            ),
            nullable=False,
        ),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("egg", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("solver_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "game_date", "guess"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userhistory")
    op.drop_table("user")
    # ### end Alembic commands ###
