"""add indices

Revision ID: edef17c40466
Revises: 8798f64b5f19
Create Date: 2024-03-03 14:19:35.170844

"""

from typing import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edef17c40466"
down_revision: Union[str, None] = "8798f64b5f19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_hotclue_secret_word_id"), "hotclue", ["secret_word_id"], unique=False
    )
    op.create_index(
        op.f("ix_secretword_game_date"), "secretword", ["game_date"], unique=False
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_userhistory_user_id"), "userhistory", ["user_id"], unique=False
    )
    op.create_index(
        "ux_user_id__game_date", "userhistory", ["user_id", "game_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_user_id__game_date", table_name="userhistory")
    op.drop_index(op.f("ix_userhistory_user_id"), table_name="userhistory")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_secretword_game_date"), table_name="secretword")
    op.drop_index(op.f("ix_hotclue_secret_word_id"), table_name="hotclue")
    # ### end Alembic commands ###
