name: Hooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.17"
    - name: Install Dependancies
      run: |
        uv sync --no-install-project
    - uses: pre-commit/action@v3.0.0

